// Generated by CoffeeScript 1.6.3
(function() {
  window.dexfiles = {};

  window.DexConfig = function(getters) {
    var conf, fn, m, _cache, _fn,
      _this = this;
    _cache = {};
    conf = {};
    _fn = function(m, fn) {
      return conf.__defineGetter__(m, function() {
        return _cache[m] || (_cache[m] = fn());
      });
    };
    for (m in getters) {
      fn = getters[m];
      _fn(m, fn);
    }
    return conf;
  };

}).call(this);
