// Generated by CoffeeScript 1.6.3
(function() {
  var itemsBlocked, naughtyURLs;

  itemsBlocked = 0;

  naughtyURLs = ["/resource/ContextLogResource/create/", "/resource/UserHomefeedResource/get/"];

  $(document).ready(function() {
    return $(document).ajaxSuccess(function(e, x, s) {
      var $newItems;
      if (~naughtyURLs.indexOf(s.url)) {
        $newItems = $(".pickedForYou").closest(".item:not(.related-pin)");
        itemsBlocked += $newItems.length;
        console.log("" + $newItems.length + " items blocked (total: " + itemsBlocked + ")");
        return $newItems.addClass("related-pin");
      } else {
        return console.log("URL " + s.url + " is not any of our concern.");
      }
    });
  });

}).call(this);
