// Generated by CoffeeScript 1.6.3
(function() {
  $('#shots ol.group div[data-picture]').removeAttr('data-picture').each(function() {
    var $div, retinaURL;
    $div = $(this);
    retinaURL = $('div[data-media]', $div).data('src');
    retinaURL = retinaURL.replace('_still.gif', '.gif');
    return $('<img src="' + retinaURL + '">').appendTo($div);
  });

}).call(this);
