// Generated by CoffeeScript 1.8.0
(function() {
  var _ref;

  console.group("Disable ESC on Squarespace sites");

  if (typeof (typeof Static !== "undefined" && Static !== null ? (_ref = Static.SQUARESPACE_CONTEXT) != null ? _ref.websiteSettings : void 0 : void 0) === "object") {
    console.log("Squarespace detected, useEscapeKeyToLogin =", Static.SQUARESPACE_CONTEXT.websiteSettings.useEscapeKeyToLogin);
    Static.SQUARESPACE_CONTEXT.websiteSettings.useEscapeKeyToLogin = false;
    console.log("useEscapeKeyToLogin set to false");
  } else {
    console.log("No Squarespace in here...");
  }

  console.groupEnd();

}).call(this);
