// Generated by CoffeeScript 1.6.3
(function() {
  (function(d, $) {
    return $(document).ready(function() {
      setTimeout(function() {
        $('.twotimes').click();
      }, 1000);
    });
  })(dex.config, dex.utils.jquery);

}).call(this);
