// Generated by CoffeeScript 1.8.0
(function() {
  var itemsBlocked, naughtyURLs;

  itemsBlocked = 0;

  naughtyURLs = ["/resource/ContextLogResource/create/", "/resource/UserHomefeedResource/get/", "/resource/UpdatesResource/get/"];

  $(document).ready(function() {
    return $(document).ajaxSuccess(function(e, x, s) {
      var $newItems, url;
      url = s.url.split("?")[0];
      if (~naughtyURLs.indexOf(url)) {
        $newItems = $(".recommendationReason").closest(".item:not(.related-pin)");
        itemsBlocked += $newItems.length;
        console.log("" + $newItems.length + " items blocked (total: " + itemsBlocked + ")");
        return $newItems.addClass("related-pin");
      } else {
        return console.log("URL " + url + " is not any of our concern.");
      }
    });
  });

}).call(this);
