// Generated by CoffeeScript 1.8.0
(function() {
  var x;

  x = $(".content").find("a").each(function() {
    var ext, href, img;
    href = $(this).attr("href");
    ext = '';
    if (!$(this).hasClass("drowsapMorphed") && $(this).next(".drowsapMorphed").length === 0) {
      if (href && (href.indexOf('imgur') >= 0 || href.indexOf('jpeg') >= 0 || href.indexOf('jpg') >= 0 || href.indexOf('png') >= 0)) {
        if (href.indexOf('imgur') >= 0 && href.indexOf('jpg') < 0 && href.indexOf('png') < 0) {
          ext = '.jpg';
        }
        console.log("" + href + ext);
        return img = $("<a class='drowsapMorphed' href='" + href + "' target='blank' style='border: 10px solid #333; display:block'><img style='display:block;max-width:780px;' src='" + href + ext + "' /></a>");
      }
    }
  });

}).call(this);
