// Generated by CoffeeScript 1.8.0
(function() {
  var seeYa;

  seeYa = setInterval(function() {
    document.body.innerHTML = "";
    document.title = "NOPE";
  }, 500);

  setTimeout(function() {
    return clearInterval(seeYa);
  }, 10000);

}).call(this);
