// Generated by CoffeeScript 1.8.0
(function() {
  var seeYa;

  seeYa = function() {
    document.body.innerHTML = '';
    document.title = 'That’s gonna be a no.';
    console.log("GTFO already");
  };

  setInterval(seeYa, 2000);

  seeYa();

}).call(this);
