// Generated by CoffeeScript 1.8.0
(function() {
  document.addEventListener("DOMContentLoaded", function(e) {
    var imgs;
    console.log("DOMContentLoaded");
    imgs = document.querySelectorAll("img[src*='/member-status-icons/']:not([src*='/member-status-icons/large/'])");
    return [].forEach.call(imgs, function(img) {
      console.info(img);
      return img.src = img.src.replace("/member-status-icons/", "/member-status-icons/large/");
    });
  });

}).call(this);
