// Generated by CoffeeScript 1.6.3
(function() {
  var shot, _fn, _i, _len;

  if (typeof SHOTS !== 'undefined') {
    _fn = function(shot) {
      var $div, $shot, retinaURL;
      $shot = $("#screenshot-" + shot.id);
      $div = $('div[data-picture]', $shot).removeAttr('data-picture');
      retinaURL = $('div[data-media]', $div).data('src').replace('_still.gif', '.gif');
      if (~retinaURL.indexOf("_1x.")) {
        $shot.addClass('retina-shot');
      }
      return $div.after("<img src='" + retinaURL + "'>").remove();
    };
    for (_i = 0, _len = SHOTS.length; _i < _len; _i++) {
      shot = SHOTS[_i];
      _fn(shot);
    }
  } else {
    console.log('Not on a shot grid page!');
  }

}).call(this);
