// Generated by CoffeeScript 1.8.0
(function() {
  var e, images;

  try {
    document.querySelector('meta[name=pinterest]').name = 'please-pin-anything';
    console.log("Removed nopin meta tag. Go forth and pin!");
  } catch (_error) {
    console.log("nopin meta tag was not found.");
  }

  try {
    images = document.querySelectorAll('img[nopin]');
    if (!images.length) {
      throw "No unpinnable images found.";
    }
    images.forEach(function(img) {
      console.log("- " + img.src + " is now pinnable.");
      return img.removeAttribute('nopin');
    });
  } catch (_error) {
    e = _error;
    console.log(e);
  }

}).call(this);
